version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
      timezone: "Europe/Berlin"
    groups:
      npm-all:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "Dependabot"
